### ISSUE TITLE
What model is it downloading of size 10.2GB ?

### ISSUE THREAD

**Issue by scarbain** [vislearn/ControlNet-XS#1]
Hi,

Thanks for the release of both the code and models.

I've set the path to the SDXL checkpoint and canny checkpoint in the config file but the inference code is still trying to download a checkpoint "ip_pytorch_model.bin" of 10.2GB. 

What is it ?

Thanks

**Comment by Sipirius** [comment]
Hi,

if you mean the example code from the readme.md with "inference code", then the only additional download is the midas checkpoint with 470mb. When is your download happening?

cheers

**Comment by CS123n** [comment]
Hey, this is the ckpt file for clip and it's around 10GB.
