### ISSUE TITLE
how to create config to train this model

### ISSUE THREAD

**Issue by zdxpan** [vislearn/ControlNet-XS#11]
how to create config to train this model

**Comment by RyannDaGreat** [comment]
Yes, are there any docs on how to train this?

**Comment by Sipirius** [comment]
Training functionality is added to the repo - [Readme Addition](https://github.com/vislearn/ControlNet-XS?tab=readme-ov-file#sd-15--21)

You would need to adapt the example dataset [`ldm.data.dummy_set.DummyBase`](https://github.com/vislearn/ControlNet-XS/blob/main/ldm/data/dummy_set.py) to your specific needs.

cheers
