### ISSUE TITLE
About ControlNet harmless

### ISSUE THREAD

**Issue by Hazarch** [vislearn/ControlNet-XS#16]
When I loaded SDXL and Control checkpoints, the model produced pictures normally. But the model generates noise when I load only SDXL's ckpt. According to the zero layer processing in the paper, should the model be consistent with SDXL at this time?

**Comment by Sipirius** [comment]
The models from the provided SDXL checkpoints additionally learn a different time embedding which is then also being used by the base model.

cheers

**Comment by Hazarch** [comment]
> The models from the provided SDXL checkpoints additionally learn a different time embedding which is then also being used by the base model.
> 
> cheers

Thank you for your prompt reply. The problem has been solved.
