### ISSUE TITLE
Training scripts and working with diffusers

### ISSUE THREAD

**Issue by aseemkhanduja** [vislearn/ControlNet-XS#23]
Thanks a lot for building this. I have 2 questions - 
1. Is there a way to make this work in diffusers? 
2. When do you plan to release the training scripts?

**Comment by Sipirius** [comment]
Hi there,

1: it seems to be currently in the making: [diffusers-integration](https://github.com/huggingface/diffusers/pull/5827)
2: hopefully as soon as possible

Cheers

**Comment by aseemkhanduja** [comment]
Thank you so much @Sipirius 
Also found the training script https://github.com/UmerHA/diffusers/tree/cnxs-training/examples/controlnet_xs . Not tested it yet. But can be useful for anyone else looking
