### ISSUE TITLE
How to train?

### ISSUE THREAD

**Issue by zhaoyuan1209** [vislearn/ControlNet-XS#24]
How to train?I haven't seen any tutorials about training

**Comment by aseemkhanduja** [comment]
https://github.com/UmerHA/diffusers/tree/cnxs-training/examples/controlnet_xs  I found this link. You can check this out

**Comment by xinli2008** [comment]
do you try controlnet-xs with inpaint ?

**Comment by Sipirius** [comment]
Training functionality is added to the repo - [Readme Addition](https://github.com/vislearn/ControlNet-XS?tab=readme-ov-file#sd-15--21)

You would need to adapt the example dataset [`ldm.data.dummy_set.DummyBase`](https://github.com/vislearn/ControlNet-XS/blob/main/ldm/data/dummy_set.py) to your specific needs.

The original ControlNet-XS model is not trained with inpaint.

cheers
