### ISSUE TITLE
About a Possible Mistake in the Condition Input of the Control Model Architecture

### ISSUE THREAD

**Issue by faruknane** [vislearn/ControlNet-XS#28]
Hi,

I have been learning the codebase. I noticed that there might be a mistake in the way of giving the condition. In the original ControlNet paper, the input condition is described as in the following image (I am using the control net paper visual since it is more detailed, I know that the architecture is not the same as ControlNet):
![image](https://github.com/user-attachments/assets/844514a7-8563-47fc-a1d1-c89a46adae55)

Meaning that the condition **c** is processed by the **zero_conv** layer and then the input **z** is added. So, the result of this is the input of the first encoder block of the control net.

In the code, the output of **zero_conv** is denoted as **guided_hint** and the condition **c** is as **h_ctr or h_base**.
![image](https://github.com/user-attachments/assets/8bde5e20-07db-443e-a0b7-7d6391d64363)

The mistake seems to be here in this code below:
![image](https://github.com/user-attachments/assets/20bb571d-f526-4497-b1b8-71292f6a9346)

Instead of **first** adding the **input (h_ctr)** to the **guided_hint**,  **h_ctr** is given to the first encoder block of the control net without **addition of guided_hint**. 

So If I were to visualize the actual code, the architecture would look like this:
![image](https://github.com/user-attachments/assets/9b6afda3-2dfe-4167-9fe7-b9c5dcef63c8)

Is there any explanation for this?

Thank you!

**Comment by faruknane** [comment]
Is this because of the first layer not being considered as an encoder block?

the first layer of the UNET:
![image](https://github.com/user-attachments/assets/8e61f639-1d20-4028-9842-9b31c2faf3b0)

**Comment by Sipirius** [comment]
Hi and thanks for the interest.

As you mention, the shown illustration is from the original ControlNet paper. The ControlNet-XS architecture and the initial processing is slightly changed as shown in the papers supplement: 
![grafik](https://github.com/user-attachments/assets/a52155e4-ba1b-4773-acb6-01311afc2b83)

We consider the first layer as a special case closer to preprocessing of the input. Hence, the control signal is added after the very fist "prepocessing" layer.


Cheers

**Comment by faruknane** [comment]
Such a beautiful world we are living in. Thank god for this.

@Sipirius thank you for the explanation, the code is well written and well organized. It is not very hard to understand even though it is really complex 😃.

Have a good sunday!
