### ISSUE TITLE
Where ControlNet-XS model code  file in whole  code ?

### ISSUE THREAD

**Issue by motion-dream** [vislearn/ControlNet-XS#3]
Your work is good! 
I want to learn from your work. Can you tell ControlNet-XS model position, I can't find it.
Thank you.   @_@

**Comment by Sipirius** [comment]
You can see in the inference config file what module is loaded.
For control of SDXL it is 
```
network_config:
      target: sgm.modules.diffusionmodules.twoStreamControl.TwoStreamControlNet
```
for control of SDv2.1 it is 
```
control_stage_config:
      target: ldm.modules.diffusionmodules.twoStreamControl.TwoStreamControlNet
```

cheers
