### ISSUE TITLE
How to train ControlNet-XS with my own dataset?

### ISSUE THREAD

**Issue by hackmebroo** [vislearn/ControlNet-XS#5]
Great Job! How to train ControlNet-XS with my own dataset?

**Comment by Whoo-jl** [comment]
I have the same problem

**Comment by universewill** [comment]
same problem here

**Comment by zdxpan** [comment]
i`m trying , only succ on sd2.1 
 but it is not yet refined enough. 
We are still in the process of experimenting with training on SDXL and making modifications to the input, data shape, format, and other areas. 

We have initiated a pull request (PR) and would appreciate everyone's feedback and collaboration to further improve the model. Let's engage in more discussions and exchanges.

**Comment by universewill** [comment]
any help here？ @Sipirius

**Comment by Sipirius** [comment]
The initial project was purely for inference and testing. However, we will probably release the training scripts at some point next month.

Cheers

**Comment by shoutOutYangJie** [comment]
> The initial project was purely for inference and testing. However, we will probably release the training scripts at some point next month.
> 
> Cheers

do you plan open the training code?

**Comment by ifsheldon** [comment]
+1. Huge boost for the community if you can open-source the training script.

**Comment by aseemkhanduja** [comment]
Will be great to have the training scripts please :)

**Comment by oxysoft** [comment]
+1 also wondering

**Comment by Sipirius** [comment]
The training script will be released approximately next week.

cheers

**Comment by Sipirius** [comment]
Training functionality is added to the repo - [Readme Addition](https://github.com/vislearn/ControlNet-XS?tab=readme-ov-file#sd-15--21)

You would need to adapt the example dataset [`ldm.data.dummy_set.DummyBase`](https://github.com/vislearn/ControlNet-XS/blob/main/ldm/data/dummy_set.py) to your specific needs.

cheers
