### ISSUE TITLE
Weird results after updating controlnet-xs + sdxl from controlnet + sdxl

### ISSUE THREAD

**Issue by LoveU3tHousand2** [vislearn/ControlNet-XS#8]
I have been fine-tuning sdxl with controlnet for remote-sensing images of buildings and the seg-map as control, but when I tried your work , the sample results became weird...
This is my controlnet+sdxl result below:
![image](https://github.com/vislearn/ControlNet-XS/assets/69668084/72b5d4b6-b863-45b3-a299-23be85b5ef45)
And this is controlnet-XS + sdxl:
![image](https://github.com/vislearn/ControlNet-XS/assets/69668084/06999809-d3b3-4e89-80d8-18d11625b24d)
We can see difference between those two results, controlnet is more natural and controlnet-xs is weird.
Is that normal or I missed some detail ?

**Comment by Sipirius** [comment]
Because of the vast redundancy in parameters in the original ControlNet, it can be a little easier to finetune to different tasks. From the looks of it you would "just"  have to find the right training parameters.

Cheers

**Comment by LoveU3tHousand2** [comment]
> Because of the vast redundancy in parameters in the original ControlNet, it can be a little easier to finetune to different tasks. From the looks of it you would "just" have to find the right training parameters.
> 
> Cheers

Thanks for explain, another question I want to know is how to initialize the weight of controlnex-xs if we don't copy it from unet? all zero or ... ?

**Comment by Sipirius** [comment]
The initialisation schedule is the same as for all other modules of the StableDiffusion U-Net. So some weights are initialised randomly, some with zeros.
